export const equipment = [
    {
        id:1,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'М\'єлнір',
        description: 'М\'єлнір - молот бога грому Тора, що символізує силу та захист у скандинавській міфології.',
        resource: 'посилання на джерело',
    },
    {
        id:2,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Драккар',
        description: 'Драккар - великий, довгий вікінгський корабель з великим вітрилом, який використовувався для військових походів і торгівлі.',
        resource: 'посилання на джерело',
    },
    {
        id:3,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Рунічні камені',
        description: 'Рунічні камені - кам\'яні плити з вирубаними рунами, які використовувалися для написання текстів, заклинань та символіки.',
        resource: 'посилання на джерело',
    },
    {
        id:4,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Берсерк',
        description: 'Берсерки - вікінги, які входили в бойовий транс та воювали без будь-якого страху або відчуття болю.',
        resource: 'посилання на джерело',
    },
    {
        id:5,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Шоломи вікінгів',
        description: 'Шоломи вікінгів - металеві головні убори з різноманітними орнаментами та візерунками, що використовувалися для захисту голови від ударів.',
        resource: 'посилання на джерело',
    },
    {
        id:6,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Лонгхаус',
        description: 'Лонгхаус - великий дерев\'яний будинок, що використовувався вікінгами як житло та місце для зборів і святкувань.',
        resource: 'посилання на джерело',
    },
    {
        id:7,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Саги',
        description: 'Саги - літературні твори, що описують історії, події та легенди вікінгів та їхні подвиги.',
        resource: 'посилання на джерело',
    },
    {
        id:8,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Торшери',
        description: 'Торшери - факели, які використовувалися вікінгами для освітлення під час нічних походів або у ритуальних церемоніях.',
        resource: 'посилання на джерело',
    },
    {
        id:9,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Одін',
        description: 'Одін - головний бог у скандинавській міфології, відомий своєю мудрістю, військовим мистецтвом та магією.',
        resource: 'посилання на джерело',
    },
    {
        id:10,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Троянди Мейра',
        description: 'Троянди Мейра - символ, який часто пов\'язують з вікінгами, він використовувався для лічби часу та навігації.',
        resource: 'посилання на джерело',
    },
    {
        id:11,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Костюми вікінгів',
        description: 'Костюми вікінгів - відповідали практичним потребам і клімату, часто складалися з вовняних тунік, штанів та міхів.',
        resource: 'посилання на джерело',
    },
    {
        id:12,
        image: 'https://www.pngitem.com/pimgs/m/496-4967836_viking-rune-of-odin-tattoo-hd-png-download.png',
        title: 'Шпаги',
        description: 'Шпаги - один з видів зброї вікінгів, що використовувався для різанини в ближньому бою.',
        resource: 'посилання на джерело',
    }
];
